# Generated by Django 4.2.2 on 2023-06-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_subject_devoir'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='correction',
            field=models.FileField(upload_to='data/<django.db.models.fields.CharField>/corrections/'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='devoir',
            field=models.FileField(null=True, upload_to='data/<django.db.models.fields.CharField>/devoirs/'),
        ),
    ]
