# Generated by Django 4.2.2 on 2023-06-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_subject_username_alter_subject_correction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='username',
        ),
        migrations.AlterField(
            model_name='subject',
            name='correction',
            field=models.FileField(upload_to='data/<django.db.models.fields.related.ForeignKey>/corrections/'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='devoir',
            field=models.FileField(null=True, upload_to='data/<django.db.models.fields.related.ForeignKey>/devoirs/'),
        ),
    ]
