# Generated by Django 4.2.2 on 2023-06-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_subject_username_alter_subject_correction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='correction',
            field=models.FileField(upload_to='data/corrections/'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='devoir',
            field=models.FileField(null=True, upload_to='data/devoirs/'),
        ),
    ]
