C=agcc
CFLAGS=-W -Wall std=c99
LOFLAGS=
EXEC=app
RC= mini_memory.c mini_string.c mini_io.c main.c
OBJ= $(SRC: ,c=,o)

all: $(EXEC)

app: $(OBJ)
	$(CC) -o $a $^ $(LDFLAGS)

%.0: %.0
	$(CC) -o $0 -c $< $(CFLAGS)

.PHONY: clean mrproper

clean:
	rm -rf * o

mrproper: clean
	rm -rf $(EXEC)