# Generated by Django 4.2.2 on 2023-06-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0002_alter_data_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
    ]
